@extends('layouts.app', ['title' => $type === 'bugs' ? 'Laporkan Bug' : 'Request Fitur'])

@section('content')
<div class="max-w-4xl mx-auto space-y-6"><a href="{{ route($type === 'bugs' ? 'feedback.bugs.index' : 'feedback.features.index') }}" class="text-xs text-slate-400">← Kembali</a><div><h1 class="text-2xl font-black text-white">{{ $type === 'bugs' ? 'Laporkan Bug' : 'Request Fitur' }}</h1><p class="text-xs text-slate-400 mt-1">Isi informasi sedetail mungkin agar tim dapat menindaklanjuti dengan cepat.</p></div>
<form method="POST" action="{{ route($type === 'bugs' ? 'feedback.bugs.store' : 'feedback.features.store') }}" enctype="multipart/form-data" class="glass-card rounded-2xl p-6 space-y-5 border border-slate-800">@csrf
    <div><label class="label">Judul *</label><input name="title" value="{{ old('title') }}" required maxlength="180" class="input" placeholder="Ringkasan singkat"></div>
    <div class="grid md:grid-cols-2 gap-4"><div><label class="label">Kategori *</label><select name="category" required class="input">@foreach($categories as $category)<option value="{{ $category }}">{{ ucfirst(str_replace('_', ' ', $category)) }}</option>@endforeach</select></div><div><label class="label">{{ $type === 'bugs' ? 'Tingkat Keparahan' : 'Prioritas' }} *</label><select name="{{ $type === 'bugs' ? 'severity' : 'priority' }}" required class="input">@foreach($type === 'bugs' ? ['low','normal','high','critical'] : ['low','normal','high'] as $level)<option value="{{ $level }}">{{ ucfirst($level) }}</option>@endforeach</select></div></div>
    <div><label class="label">Deskripsi {{ $type === 'bugs' ? 'masalah' : 'fitur' }} *</label><textarea name="description" required rows="5" class="input" placeholder="Jelaskan konteks dan kebutuhan secara lengkap">{{ old('description') }}</textarea></div>
    @if($type === 'bugs')
        <div><label class="label">Langkah Reproduksi</label><textarea name="steps_to_reproduce" rows="4" class="input"></textarea></div><div class="grid md:grid-cols-2 gap-4"><div><label class="label">Hasil yang Diharapkan</label><textarea name="expected_behavior" rows="3" class="input"></textarea></div><div><label class="label">Hasil Aktual</label><textarea name="actual_behavior" rows="3" class="input"></textarea></div></div><div><label class="label">Environment / Perangkat</label><input name="environment" class="input" placeholder="Contoh: Chrome 126, Windows 11, outlet Jakarta"></div><div><label class="label">Lampiran screenshot/log</label><input type="file" name="attachment" accept=".jpg,.jpeg,.png,.webp,.pdf,.txt,.log" class="input"></div>
    @else
        <div><label class="label">Nilai Bisnis *</label><textarea name="business_value" required rows="3" class="input" placeholder="Dampak positif untuk bisnis"></textarea></div><div><label class="label">Contoh Use Case *</label><textarea name="use_case" required rows="3" class="input" placeholder="Siapa yang menggunakan dan bagaimana alurnya"></textarea></div><div><label class="label">Solusi yang Diusulkan</label><textarea name="proposed_solution" rows="3" class="input"></textarea></div>
    @endif
    <button class="px-5 py-3 rounded-xl bg-emerald-500 text-slate-950 font-bold text-sm">Kirim {{ $type === 'bugs' ? 'Laporan Bug' : 'Request Fitur' }}</button>
</form></div>
@endsection
@push('styles')<style>.label{display:block;color:#cbd5e1;font-size:.75rem;font-weight:700;margin-bottom:.4rem}.input{width:100%;background:#020617;border:1px solid #1e293b;border-radius:.75rem;padding:.7rem;color:#f8fafc;font-size:.8rem}.input:focus{border-color:#22d3ee;outline:none}</style>@endpush
